apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-alertmanager.fullname" . }}
  labels:
    {{- include "matrix-alertmanager.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_PORT: "{{ .Values.config.app_port }}"
  APP_ALERTMANAGER_SECRET: "{{ .Values.config.app_alertmanager_secret }}"
  MATRIX_HOMESERVER_URL: "{{ .Values.config.matrix_homeserver_url }}"
  MATRIX_ROOMS: "{{ .Values.config.matrix_rooms }}"
  MATRIX_TOKEN: "{{ .Values.config.matrix_token }}"
  MATRIX_USER: "{{ .Values.config.matrix_user }}"
  MENTION_ROOM: "{{ .Values.config.mention_room }}"
